[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "dd31a70e2bcf15dc499fbe93cb9c0dfb80b6bbd2"
os = "macos"

    [[AMGCL_C.download]]
    sha256 = "c03da98142f0515b340c72f519a4f1a1310d27511b150fa7de731ee61de1e33c"
    url = "https://github.com/j-fu/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.2+0/AMGCL_C.v0.2.2.x86_64-apple-darwin.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "61eb504443d86f72bedfafa827d2bffd34651b81"
libc = "glibc"
os = "linux"

    [[AMGCL_C.download]]
    sha256 = "0da71083a1433765b7625153a7f40621caf8c3626b63fda6c877fcb17a393e28"
    url = "https://github.com/j-fu/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.2+0/AMGCL_C.v0.2.2.x86_64-linux-gnu.tar.gz"
[[AMGCL_C]]
arch = "x86_64"
git-tree-sha1 = "2f1f6cf4d857c38fb803409c52b06198f61baad1"
os = "windows"

    [[AMGCL_C.download]]
    sha256 = "c24d6b990ddfb63848a9c17e6a068bdedccee94a7bb8462959eb3dfc0d730cd1"
    url = "https://github.com/j-fu/AMGCL_C_jll.jl/releases/download/AMGCL_C-v0.2.2+0/AMGCL_C.v0.2.2.x86_64-w64-mingw32.tar.gz"
